contact_links:
  - name: Larry Studios Community Discord
    url: https://discord.gg/CZNQEHRSwX
    about: Need further help? Join our official Discord!
  - name: Brain Hurt Games Discussion
    url: https://github.com/larrystudios/brainhurtgames/discussions
    about: Discuss with other players here!
